allowBuilds:
  '@reown/appkit': false
  bufferutil: false
  keccak: false
  sharp: false
  unrs-resolver: false
  utf-8-validate: false
minimumReleaseAgeExclude:
  - '@privy-io/js-sdk-core@0.78.2'
  - '@privy-io/react-auth@3.48.1'
  - '@privy-io/routes@0.4.4'
